---
kind: pipeline
type: docker
name: build-notag

platform:
  os: linux
  arch: amd64

steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: guessi/drone
    dry_run: true
  when:
    event:
      include:
      - pull_request

- name: image-build
  image: plugins/docker
  settings:
    repo: guessi/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - 2.7.2
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

trigger:
  branch:
    include:
    - master

---
kind: pipeline
type: docker
name: build-nolimit

platform:
  os: linux
  arch: amd64

steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: guessi/drone
    dry_run: true
    build_args:
    - "BUILD_TAGS=nolimit"
  when:
    event:
      include:
      - pull_request

- name: image-build
  image: plugins/docker
  settings:
    repo: guessi/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - 2.7.2-nolimit
    - nolimit
    build_args:
    - "BUILD_TAGS=nolimit"
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

trigger:
  branch:
    include:
    - master

---
kind: pipeline
type: docker
name: build-nolimit-oss

platform:
  os: linux
  arch: amd64

steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: guessi/drone
    dry_run: true
    build_args:
    - "BUILD_TAGS=nolimit oss"
  when:
    event:
      include:
      - pull_request

- name: image-build
  image: plugins/docker
  settings:
    repo: guessi/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - 2.7.2-nolimit-oss
    - nolimit-oss
    - latest
    build_args:
    - "BUILD_TAGS=nolimit oss"
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

trigger:
  branch:
    include:
    - master

...
