---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-no-tag-pr
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    context: .
    repo: guessi/drone
    dry_run: true
  when:
    event:
      include:
      - pull_request

- name: build-no-tag
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    context: .
    repo: guessi/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - 1.9.2
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

trigger:
  branch:
    include:
    - master

---
kind: pipeline
type: docker
name: enterprise-nolimit

platform:
  os: linux
  arch: amd64

steps:
- name: build-nolimit-pr
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.nolimit
    context: .
    repo: guessi/drone
    dry_run: true
  when:
    event:
      include:
      - pull_request

- name: build-nolimit
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.nolimit
    context: .
    repo: guessi/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - 1.9.2-nolimit
    - nolimit
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

trigger:
  branch:
    include:
    - master

---
kind: pipeline
type: docker
name: community-nolimit

platform:
  os: linux
  arch: amd64

steps:
- name: build-nolimit-oss-pr
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.nolimit-oss
    context: .
    repo: guessi/drone
    dry_run: true
  when:
    event:
      include:
      - pull_request

- name: build-nolimit-oss
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.nolimit-oss
    context: .
    repo: guessi/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - 1.9.2-nolimit-oss
    - nolimit-oss
    - latest
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

trigger:
  branch:
    include:
    - master

...
